// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    name,
    ip_address,
    device_type
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, ip_address, device_type, created_at, updated_at, last_seen
`

type CreateDeviceParams struct {
	Name       string
	IpAddress  string
	DeviceType string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.Name, arg.IpAddress, arg.DeviceType)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.DeviceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteDeviceByID = `-- name: DeleteDeviceByID :exec
DELETE FROM devices
WHERE id = $1
`

func (q *Queries) DeleteDeviceByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceByID, id)
	return err
}
