// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    serial_number,
    name,
    ip_address,
    device_type
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING serial_number, name, ip_address, device_type, created_at, updated_at, last_seen
`

type CreateDeviceParams struct {
	SerialNumber string
	Name         string
	IpAddress    string
	DeviceType   string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.SerialNumber,
		arg.Name,
		arg.IpAddress,
		arg.DeviceType,
	)
	var i Device
	err := row.Scan(
		&i.SerialNumber,
		&i.Name,
		&i.IpAddress,
		&i.DeviceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE serial_number = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, serialNumber string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, serialNumber)
	return err
}
