// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID         uuid.UUID
	Name       string
	IpAddress  string
	DeviceType string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastSeen   time.Time
}
