// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wdlms.sql

package database

import (
	"context"
)

const createWdlm = `-- name: CreateWdlm :one
INSERT INTO wdlms (
    name
) VALUES (
    $1
)
RETURNING id, name, created_at, updated_at, last_seen_at
`

func (q *Queries) CreateWdlm(ctx context.Context, name string) (Wdlm, error) {
	row := q.db.QueryRowContext(ctx, createWdlm, name)
	var i Wdlm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
