// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package local

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    name,
    serial_number,
    ip_address,
    firmware_version,
    device_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, DEFAULT)
)
RETURNING id, name, serial_number, ip_address, firmware_version, device_type, last_seen, created_at, updated_at
`

type CreateDeviceParams struct {
	Name            string
	SerialNumber    sql.NullString
	IpAddress       sql.NullString
	FirmwareVersion sql.NullString
	Column5         interface{}
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.Name,
		arg.SerialNumber,
		arg.IpAddress,
		arg.FirmwareVersion,
		arg.Column5,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SerialNumber,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.DeviceType,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
