// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package local

import (
	"database/sql"
	"time"
)

type Device struct {
	SerialNumber string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	IpAddress    string
	DeviceType   string
	LastSeen     sql.NullTime
}
