// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package local

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID              uuid.UUID
	Name            string
	SerialNumber    sql.NullString
	IpAddress       sql.NullString
	FirmwareVersion sql.NullString
	DeviceType      sql.NullString
	LastSeen        sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
